# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='developer',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='discussions',
            name='discus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discus', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='Project_my',
        ),
    ]
